// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// actpnts_cpp
DataFrame actpnts_cpp(std::string margdist, NumericVector margarg, double p0, double lower, double upper, double mu1, double mu2, NumericVector rhoz_vals, int max_eval, double abs_tol, double rel_tol);
RcppExport SEXP _CoSMoS_actpnts_cpp(SEXP margdistSEXP, SEXP margargSEXP, SEXP p0SEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP mu1SEXP, SEXP mu2SEXP, SEXP rhoz_valsSEXP, SEXP max_evalSEXP, SEXP abs_tolSEXP, SEXP rel_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type margdist(margdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type margarg(margargSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rhoz_vals(rhoz_valsSEXP);
    Rcpp::traits::input_parameter< int >::type max_eval(max_evalSEXP);
    Rcpp::traits::input_parameter< double >::type abs_tol(abs_tolSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(actpnts_cpp(margdist, margarg, p0, lower, upper, mu1, mu2, rhoz_vals, max_eval, abs_tol, rel_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CoSMoS_actpnts_cpp", (DL_FUNC) &_CoSMoS_actpnts_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoSMoS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
